### ISSUE TITLE
Still maintained? 

### ISSUE THREAD

**Issue by kMikaZu** [azusapacificuniversity/snipe-agent#5]
Is this process still maintained? Does it work on macOS devices?

**Comment by ParadoxGuitarist** [comment]
While I'm no longer employed at this org, it's still in use AFAIK. While I was there, we never deployed it on macOS because we elected to run syncs between JamfPro (via https://github.com/grokability/jamf2snipe ) instead of having yet another process collect data.

When we wrote this, we didn't know if we'd keep that vendor forever so we put in a lot of parts to enable it to run on macOS. You can check the go file and look for lines with `case "darwin"` and those blocks will be what'll run in macOS. 

From what I recall, the agent should run, but collects very little data by default and there's not an installer to register a service like there is for Windows. I can't speak for the team, but I would image that PRs are still probably welcome if you want to use what's already here.

**Comment by drewbeedooo** [comment]
Yep, we're still using it, but only for Windows as we're still using the jamf2snipe sync that @ParadoxGuitarist mentioned. PRs are welcome; we don't have plans to develop the MacOS case ourselves at the moment. I imagine it wouldn't take too much effort to setup the darwin case with commands that get desired information, but figuring out how to get it to run as a daemon might be a pain.
